### ISSUE TITLE
NBViewer missing page title / meta description

### ISSUE THREAD

**Issue by dimo414** [jupyter/nbviewer#164]
I noticed while trying to share Peter Norvig's Notebook on [XKCD 1313](http://nbviewer.ipython.org/url/norvig.com/ipython/xkcd1313.ipynb) that NBViewer doesn't provide useful title/description for Facebook shares, and more generally doesn't specify a page title or meta description:

```
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
```

This leads to a poor user experience, as search engines will have a harder time identifying valuable keywords, and sharing services like Facebook will use poor default values:

![facebooksharebug](https://f.cloud.github.com/assets/1885701/1889747/a0485910-7a21-11e3-9c13-58965f468ef4.png)

**Comment by parente** [comment]
`title` (https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json#L63) and `authors` (https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json#L67) are now part of the notebook v4 schema.

**Comment by westurner** [comment]
- [ ] Extract ``notebook_title``
- [x] Add ``notebook_title`` Twitter Card metadata
- [ ] Add ``notebook_title`` OpenGraph metadata
- [ ] Add ``notebook_title`` Schema.org metadata

.

- https://github.com/jupyter/nbviewer/blob/master/nbviewer/templates/notebook.html
- https://github.com/CodeForAntarctica/codeforantarctica.github.io/pull/3 (schema docs links)
